[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
exclude = ^.*site-packages.*

[mypy-mcp]
ignore_errors = True

[mypy-mcp.client.sse]
ignore_errors = True

[mypy-pyaudio.*]
ignore_errors = True

[mypy-faster_whisper.*]
ignore_errors = True

[mypy-PyQt6.*]
ignore_errors = True
