[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
check_untyped_defs = True
ignore_missing_imports = True
follow_imports = skip
exclude = ^.*site-packages.*$|^modules[\\/](gpt_sovits|openmanus|memory)[\\/].*$

[mypy-mcp.*]
ignore_errors = True

[mypy-pyaudio.*]
ignore_errors = True

[mypy-faster_whisper.*]
ignore_errors = True

[mypy-PyQt6.*]
ignore_errors = True
