"""
ManusAgent — 基于 OpenManus 框架的智能体同步包装

将 OpenManus 的异步 Manus agent 封装为同步的 run_task() 接口，
以便与现有的 PyQt6 主循环和 AIWorker 线程无缝集成。

架构：
  调用者 (sync)  →  ManusAgent.run_task()
                      └→  asyncio event loop (在独立线程中运行)
                            └→  OpenManus Manus agent (async)
                                  └→  ToolCallAgent.think() / act()
                                        └→  BrowserUseTool, PythonExecute, WebSearch, ...

LLM 配置统一：
  OpenManus 的 config.toml 由本模块在首次导入 OpenManus 前自动生成，
  API 设置(model, base_url, api_key)全部从项目的 .env / modules.config 中读取，
  保证单一配置源，无需手动编辑 config.toml。
"""

from __future__ import annotations

import asyncio
import os
import re
import sys
import threading

from ..logging_config import get_logger

logger = get_logger("ManusAgent")

# ---- 确保 OpenManus 在 Python path 中 ----
_OPENMANUS_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", "OpenManus"))
if _OPENMANUS_ROOT not in sys.path:
    sys.path.insert(0, _OPENMANUS_ROOT)

# ---- 标记：config.toml 是否已同步 ----
_config_synced = False


def _sync_openmanus_config():
    """将项目的 LLM API 设置同步写入 OpenManus 的 config.toml。

    核心思路：项目的 .env 是唯一配置源，OpenManus 的 config.toml 只是它的
    派生文件，每次 ManusAgent 初始化时自动重新生成，开发者无需手动维护。

    读取来源：
      - ARK_API_KEY       → .env（通过 os.environ，已由 modules.config 的 load_dotenv 加载）
      - ARK_BASE_URL      → .env（可选，默认 https://ark.cn-beijing.volces.com/api/v3）
      - MODEL_NAME        → .env / modules.config.MODEL_NAME
    """
    global _config_synced
    if _config_synced:
        return

    from ..config import MODEL_NAME

    api_key = os.environ.get("ARK_API_KEY", "")
    base_url = os.environ.get("ARK_BASE_URL", "https://ark.cn-beijing.volces.com/api/v3")
    model = MODEL_NAME or "deepseek-v3-250324"

    config_dir = os.path.join(_OPENMANUS_ROOT, "config")
    os.makedirs(config_dir, exist_ok=True)
    config_path = os.path.join(config_dir, "config.toml")

    toml_content = f"""\
# ╔══════════════════════════════════════════════════════════════╗
# ║  Auto-generated by modules/agent/core.py — 请勿手动编辑     ║
# ║  修改 API 设置请编辑项目根目录的 .env 文件                    ║
# ╚══════════════════════════════════════════════════════════════╝

[llm]
model = "{model}"
base_url = "{base_url}"
api_key = "{api_key}"
max_tokens = 8192
temperature = 0.0
api_type = ""
api_version = ""

[search]
engine = "Baidu"
fallback_engines = ["DuckDuckGo", "Bing"]
lang = "zh"
country = "cn"

[browser]
headless = false
disable_security = true

[mcp]
server_reference = "app.mcp.server"
"""

    try:
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(toml_content)
        _config_synced = True
        logger.info(f"OpenManus config.toml 已同步 (model={model}, base_url={base_url})")
    except Exception as e:
        logger.error(f"写入 OpenManus config.toml 失败: {e}")
        raise


class ManusAgent:
    """OpenManus Manus agent 的同步包装。

    对外暴露 ``run_task(task_description) -> str`` 接口，
    内部通过独立的 asyncio 事件循环运行 OpenManus 的异步 Manus agent。

    LLM 设置自动从项目 .env 中读取，无需额外配置。

    Parameters
    ----------
    system_prompt : str, optional
        附加的 system prompt（会注入到 Manus agent 中）。
    max_steps : int
        最大执行步骤数，默认 100。
    """

    def __init__(
        self,
        system_prompt: str = "",
        max_steps: int = 100,
    ):
        self.system_prompt = system_prompt or ""
        self.max_steps = max_steps
        self._agent = None  # 延迟创建（在 async 上下文中初始化）
        self._loop: asyncio.AbstractEventLoop | None = None
        self._loop_thread: threading.Thread | None = None
        self._initialized = False

        # 在任何 OpenManus 模块被导入之前，先将项目 API 设置同步到 config.toml
        _sync_openmanus_config()

        logger.info(f"ManusAgent 初始化 (OpenManus 后端, max_steps={self.max_steps})")

        # 启动后台事件循环线程
        self._start_event_loop()

    def _start_event_loop(self):
        """启动一个持久的后台 asyncio 事件循环线程。"""
        ready = threading.Event()

        def _run_loop():
            self._loop = asyncio.new_event_loop()
            asyncio.set_event_loop(self._loop)
            ready.set()
            self._loop.run_forever()

        self._loop_thread = threading.Thread(target=_run_loop, daemon=True)
        self._loop_thread.start()
        ready.wait(timeout=5)
        logger.debug("后台 asyncio 事件循环已启动")

    def _run_coro(self, coro):
        """在后台事件循环中运行协程并同步等待结果。"""
        if self._loop is None or self._loop.is_closed():
            raise RuntimeError("后台事件循环未启动或已关闭")
        future = asyncio.run_coroutine_threadsafe(coro, self._loop)
        return future.result()  # 阻塞等待

    async def _ensure_agent(self):
        """确保 OpenManus Manus agent 已创建（延迟初始化）。"""
        if self._agent is not None:
            return

        # 延迟导入 — config.toml 此时已由 __init__ 中的 _sync_openmanus_config() 写好
        from app.agent.manus import Manus
        from app.config import config

        # 构建自定义的 system prompt
        base_prompt = (
            "你是一个强大的 AI 智能体，能够解决用户提出的各种任务。你拥有多种工具可以调用，"
            "包括浏览器自动化、Python 代码执行、文件编辑、网页搜索等。"
            "请用中文回答和思考。"
            "严禁将纯文本内容直接写入 .pptx/.docx/.xlsx/.pdf 这类二进制格式文件。"
            "若用户要求生成 PPTX，必须通过 python_execute 运行 Python 代码生成合法的 Office 文件。"
            f"\n工作目录: {config.workspace_root}"
        )
        if self.system_prompt:
            base_prompt = self.system_prompt + "\n\n" + base_prompt

        self._agent = await Manus.create(
            system_prompt=base_prompt,
            max_steps=self.max_steps,
        )
        self._initialized = True
        logger.info("OpenManus Manus agent 创建成功")

    def run_task(self, task_description: str) -> str:
        """执行给定任务（同步、阻塞）并返回最终结果字符串。

        Parameters
        ----------
        task_description : str
            任务描述文本。

        Returns
        -------
        str
            Agent 执行结果的文本摘要。
        """
        logger.info(f"ManusAgent.run_task — task={task_description[:200]}")

        try:
            result = self._run_coro(self._async_run_task(task_description))
            logger.info(
                f"ManusAgent.run_task 完成 — result(len)=" f"{len(result) if isinstance(result, str) else 'N/A'}"
            )
            return result
        except Exception as e:
            logger.exception(f"ManusAgent.run_task 异常: {e}")
            return f"❌ Agent 执行异常: {e}"

    async def _async_run_task(self, task_description: str) -> str:
        """异步执行任务（在后台事件循环线程中运行）。"""
        await self._ensure_agent()

        task_description = self._prepare_task_description(task_description)

        try:
            # 重置 agent 状态以便重复使用
            from app.schema import AgentState

            self._agent.state = AgentState.IDLE
            self._agent.current_step = 0
            self._agent.memory.clear()

            # 运行任务
            result = await self._agent.run(task_description)
            return result
        except Exception as e:
            logger.exception(f"OpenManus agent 执行失败: {e}")
            return f"❌ Agent 内部错误: {e}"

    def _prepare_task_description(self, task_description: str) -> str:
        """根据任务类型注入约束，降低错误工具调用概率。"""
        normalized = (task_description or "").lower()
        result = task_description

        # 检测 B 站/视频网站任务
        is_bilibili_task = bool(
            re.search(r"(b站|bilibili|哔哩哔哩)", normalized) and re.search(r"(视频|播放|搜索|看|打开)", normalized)
        )
        if is_bilibili_task:
            bilibili_suffix = (
                "\n\n【B站视频任务执行策略】\n"
                "1) 不要使用百度搜索B站视频，直接使用 go_to_url 访问 https://search.bilibili.com/all?keyword=你的搜索词\n"
                "2) 在B站搜索结果页，使用 extract_content 提取视频标题和完整URL（包含BV号）\n"
                "3) 使用 go_to_url 直接访问提取到的视频URL（类似 https://www.bilibili.com/video/BVxxxxxxx）\n"
                "4) 导航到视频页面后使用 get_media_status 验证视频是否播放\n"
                "5) 不要在页面上盲目点击元素索引，索引1-10通常是导航栏（首页/番剧/直播等），不是视频\n"
                "6) 视频播放中即可调用 terminate 完成任务"
            )
            result += bilibili_suffix

        # 检测 PPT 任务
        is_ppt_task = bool(
            re.search(r"\b(ppt|pptx|powerpoint)\b", normalized)
            or ("幻灯片" in task_description)
            or ("演示文稿" in task_description)
        )
        if is_ppt_task:
            ppt_suffix = (
                "\n\n【PPT执行约束】\n"
                "1) 不允许使用 str_replace_editor 在 .pptx 路径写入文本；\n"
                "2) 需要生成真实可打开的 .pptx 文件时，必须使用 python_execute 运行 Python 生成；\n"
                "3) 如当前环境缺少生成 PPT 所需库，请先生成同名 .md 提纲文件，并在结果中明确说明原因。"
            )
            result += ppt_suffix

        return result

    def cleanup(self):
        """清理资源。"""
        try:
            if self._agent is not None:
                self._run_coro(self._agent.cleanup())
                self._agent = None
        except Exception as e:
            logger.warning(f"Agent cleanup 异常: {e}")

        # 停止事件循环
        if self._loop and not self._loop.is_closed():
            self._loop.call_soon_threadsafe(self._loop.stop)
        if self._loop_thread:
            self._loop_thread.join(timeout=3)
        logger.info("ManusAgent 资源已清理")

    # ======= 向后兼容的学习接口（空实现）=======
    def start_learning(self, task_name: str) -> str:
        """教学模式（当前 OpenManus 后端暂不支持）。"""
        logger.info(f"start_learning called (task={task_name}) — OpenManus 后端暂不支持教学模式")
        return "⚠️ 当前 Agent 后端 (OpenManus) 暂不支持教学模式。"

    def stop_learning(self) -> str:
        """结束教学模式（空实现）。"""
        return "⚠️ 当前 Agent 后端 (OpenManus) 暂不支持教学模式。"
